config/routes.rb
TemplateHealing::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  post 'manual_select' => 'application#manual_select', as: :set_locale

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :sessions, only: [:create, :destroy]
    resources :users
    resources :pages
    resources :workshops
    resources :testimonies
    root 'pages#home'
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

  translates :title, :body

  validates :slug, uniqueness: true, presence: true

  before_validation :slugify

  def slugify
    self.slug ||= title.parameterize
  end

  def to_param
    slug
  end

end

app/models/testimony.rb
class Testimony < ActiveRecord::Base
  translates :occupation, :content
  validates_presence_of :person, :content
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :nickname, :email
  validates_uniqueness_of :nickname, :email
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  translates :title, :description
  validates :description, presence: true
  validates :position, uniqueness: true
  # validates_presence_of :title, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :fetch_pages, :set_locale
  protect_from_forgery with: :exception

  add_flash_types :error

  private

  def authorize
    redirect_to :root, error: t('users.not_authorized') unless current_user
  end

  def current_user_id
    session[:user_id]
  end

  def current_user
    @current_user ||= User.find(current_user_id) if current_user_id
  end

  def fetch_pages
    @pages = Page.all
  end

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index, :home]

  def index
    @pages = Page.all
  end

  def home
    @home = "template healing"
  end

  def show; end

  def new
    @page = Page.new
  end

  def edit; end

  # POST /pages
  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to @page, notice: t(:'pages.create.success')
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /pages/1
  def update
    if @page.update(page_params)
      redirect_to @page, notice: t(:'pages.update.success')
    else
      render action: 'edit' 
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    redirect_to :root
  end

  private
  def set_page
    @page = Page.find_by!(slug: params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    p 'sarasa'
    if session_params[:login].match(/@/)
      user = User.find_by_email(session_params[:login])
    else
      user = User.find_by_nickname(session_params[:login])
    end
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to :back, notice: t('login.success')
    else
      redirect_to :back, error: t('login.error')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: t('login.logout')
  end

  def new

  end

  private

  def session_params
    params.require(:sessions).permit(:login, :password)
  end

end

app/controllers/testimonies_controller.rb
class TestimoniesController < ApplicationController
  before_action :set_testimony, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  # GET /testimonies
  def index
    @testimonies = Testimony.all
  end

  # GET /testimonies/1
  def show
  end

  # GET /testimonies/new
  def new
    @testimony = Testimony.new
  end

  # GET /testimonies/1/edit
  def edit
  end

  # POST /testimonies
  def create
    @testimony = Testimony.new(testimony_params)

    respond_to do |format|
      if @testimony.save
        format.html { redirect_to testimonies_url, notice: t(:'testimonies.create.success') }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /testimonies/1
  def update
    respond_to do |format|
      if @testimony.update(testimony_params)
        format.html { redirect_to testimonies_url, notice: t(:'testimonies.update.success')}
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /testimonies/1
  def destroy
    @testimony.destroy
    respond_to do |format|
      format.html { redirect_to testimonies_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimony
      @testimony = Testimony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimony_params
      params.require(:testimony).permit(:person, :occupation, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  add_flash_types :error

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: t('users.create.success')
    else
      render action: 'new', error: t('users.create.error')
    end
  end

  def destroy

  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:id, :nickname, :email, :admin, :password, :password_confirmation, :_destroy)
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:show, :index]

  def index
    @workshops = Workshop.all
  end

  def show; end

  def new
    @workshop = Workshop.new
  end

  def edit; end

  # POST /workshops
  def create
    @workshop = Workshop.new(workshop_params)
    if @workshop.save
      redirect_to @workshop, notice: 'Workshop was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /workshops/1
  def update
    if @workshop.update(workshop_params)
      redirect_to @workshop, notice: 'Workshop was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /workshops/1
  def destroy
    @workshop.destroy
    redirect_to workshops_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_workshop
    @workshop = Workshop.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def workshop_params
    params.require(:workshop).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def iconize(icon)
    "<i class=\"icon-#{icon}\"></i>".html_safe unless icon.nil?
  end

  def edit_link(object)
    link_to iconize(:pencil), edit_polymorphic_path(object), data: {tooltip: t('edit')}, class: 'tooltip-top'
  end

  def new_link(object)
    link_to iconize(object.class.to_s.downcase), new_polymorphic_path(object), data: {tooltip: t('create')}, class: 'tooltip-top'

  end

  def destroy_link(object)
    link_to iconize(:trash),
      polymorphic_path(object),
      method: :delete,
      data: { confirm: t('confirmation'), tooltip: t('destroy') },
      class: 'tooltip-top'
  end

  def show_link(object)
    link_to iconize(:eye), object
  end

  def back_link
     link_to iconize(:'arrow-left'), :back
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testimonies_helper.rb
module TestimoniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/application/_admin_menu.html.erb
<li><%= link_to t('pages.new.title'), new_page_path  %></li>
<li><%= link_to t('workshops.new.title'), new_workshop_path  %></li>
<li><%= link_to t('testimonies.new.title'), new_testimony_path  %></li>
<li><%= link_to t('testimonies.sort.init'), '#', id: 'sort-testimonies'%></li>
<% if current_user.admin? %>
  <li><%= link_to t('users.new.title'), new_user_path  %></li>
<% end %>

app/views/application/_flashes.html.erb
<% if !notice.blank? %>
  <div class="alert success">
    <%= notice %>
  </div>
<% end %>
<% if !error.blank?  %>
  <div class="alert error">
    <%= error %>
  </div>
<% end %>

app/views/application/_footer.html.erb
<nav class="footer-nav">
<ul class="main-nav">
  <% I18n.available_locales.each do |locale| %>
    <li><%= nav_link_to image_tag("#{locale}.png", class: :flag) + locale.to_s, locale: locale %></li>
  <% end %>
  <li class="drop up">
  <%= iconize :users %>
  <ul class="drop-container">
    <% if current_user %>
      <%= render 'admin_menu' %>
      <li> <%= link_to t('sessions.close'), session_path('current'), method: 'delete', class: :button  %> </li>
    <% else %>
      <%= simple_form_for :sessions, { url: sessions_path} do |f| %>
        <%= f.input :login, placeholder: t('login.name_or_email') %>
        <%= f.input :password, placeholder: t('login.password') %>
        <br />
        <%= f.button :submit, t('send') %>
      <% end %>
    <% end %>
  </ul>
  </li>
</ul>
</nav>

app/views/application/_pages_nav.html.erb
<nav id="nav">
  <ul class="main-nav">
    <li><%= nav_link_to t(:'workshops.title'), controller: "workshops" %></li>
    <li><%= nav_link_to t(:'testimonies.title'), controller: "testimonies" %></li>
    <% @pages.each do |page| %>
      <li><%= nav_link_to page.title, page_path(page) %></li>
    <% end %>
    <li><%= nav_link_to 'contact', '#' %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= content_for?(:title) ? yield(:title) : "Creation Template" %></title>

  <!-- external stylesheets and fonts -->
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <!-- end external -->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body <%= 'class="admin"'.html_safe if current_user %>>

<%= render 'pages_nav' %>

<div class="wrapper">
  <div class="container">
    <%= link_to image_tag(:'logo.png'), :root, class: :logo %>
    <%= render 'flashes' %>
    <%= yield %>
  </div>
</div>

<br />
<%= render 'footer' %>

</body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <div class="field">
    <%= f.input :title %>
  </div>
  <div class="field">
    <%= f.cktext_area :body %>
  </div>
  <!-- <div class="field"> -->
  <!--   <%# f.input :visible %> -->
  <!-- </div> -->
  <div class="actions">
    <%= f.submit t(:save), class: :button %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1 class="page-title"><%= t '.title' %></h1>

<%= render 'form' %>

app/views/pages/home.html.erb
<h1 class="page-title"><%= @home %></h1>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/show.html.erb
<div class="admin-editable">
  <h1 class="page-title"><%= @page.title %></h1>
  <div class="page-body">
    <%= simple_format @page.body %>
  </div>
  <% if current_user  %>
    <div class="actions">
      <%= edit_link @page %>
      <%= destroy_link @page %>
    </div>
  <% end %>
</div>

app/views/testimonies/_form.html.erb
<%= simple_form_for(@testimony) do |f| %>
  <div class="field">
    <%= f.input :person %><br>
  </div>
  <div class="field">
    <%= f.input :occupation %><br>
  </div>
  <div class="field">
    <%= f.input :content %><br>
  </div>
  <div class="actions">
    <%= f.submit t('save'), class: :button %>
  </div>
<% end %>

app/views/testimonies/_testimony.html.erb
<div class=" col-1-2">
  <div class="testimony admin-editable">
    <section class="media attribution">
    <div class="bd">
      <%= iconize :user %>
      <a href="#" class="t-name"><%= testimony.person %></a>
      <span class="tw-occu"><%= testimony.occupation %></span>
    </div>
    <div class="info">
      <blockquote>
        <%= testimony.content %>
      </blockquote>
    </div>

    <% if current_user %>
      <div class="actions tw-actions">
        <%= edit_link testimony %>
        <%= destroy_link testimony %>
      </div>
    <% end %>
    </section>
  </div>
</div>

app/views/testimonies/edit.html.erb
<h1 class="page-title"><%= t :'.title' %></h1>

<%= render 'form' %>

app/views/testimonies/index.html.erb
<h1 class="page-title"><%= t 'testimonies.title' %> </h1>
<div class="testimonies-wrapper row">
    <%= render @testimonies %>
</div>

app/views/testimonies/new.html.erb
<h1 class="page-title"><%= t '.title' %></h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |form| %>
  <%= form.input :nickname %>
  <%= form.input :email %>
  <%= form.input :password %>
  <%= form.input :password_confirmation %>
  <%= form.input :admin, label: t('users.admin'), as: :boolean %>
  <div class="actions">
    <%= form.submit t('send'), class: :button %>
  </div>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.nickname %>
<% end %>

app/views/users/new.html.erb
<h1 class="page-title"><%= t 'users.new.title' %></h1>

<%= render 'form' %>

app/views/workshops/_form.html.erb
<%= simple_form_for(@workshop) do |f| %>
  <div class="field">
    <%= f.input :title %><br>
  </div>
  <div class="field">
    <%= f.input :description %><br>
  </div>
  <div class="actions">
    <%= f.submit t('save'), class: :button %>
  </div>
<% end %>

app/views/workshops/_workshop.html.erb
<div class="admin-editable">
  <section class="workshop">
    <h1 class="title">
      <%= link_to workshop.title, workshop %>
    </h1>
    <div class="info">
      <%= workshop.description %>
    </div>
    <% if current_user  %>
      <div class="actions">
        <%= edit_link workshop %>
        <%= destroy_link workshop %>
      </div>
    <% end %>
  </section>
</div>

app/views/workshops/edit.html.erb
<h1 class="page-title">Editing workshop</h1>

<%= render 'form' %>

app/views/workshops/index.html.erb
<h1 class="page-title"><%= t 'workshops.title' %></h1>

<div id="sortable">
  <%= render @workshops %>
  <%= link_to t('testimonies.sort.submit'), '#', id: 'submit-sort', class: :'button' %>
</div>

app/views/workshops/new.html.erb
<h1 class="page-title"><%= t :'.title' %></h1>

<%= render 'form' %>

<%= link_to t('back'), workshops_path %>

app/views/workshops/show.html.erb
<div class="admin-editable">
  <h1 class="page-title">
    <%= @workshop.title %>
  </h1>
  <%= @workshop.description %>
  <% if current_user  %>
    <div class="actions">
      <%= edit_link @workshop %>
      <%= destroy_link @workshop %>
    </div>
  <% end %>
</div>